/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandProfileRouteImport } from './routes/brand-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PastReportsRouteImport } from './routes/past-reports'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StrategyReportRouteImport } from './routes/strategy-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProfileRoute = BrandProfileRouteImport.update({
  id: '/brand-profile',
  path: '/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PastReportsRoute = PastReportsRouteImport.update({
  id: '/past-reports',
  path: '/past-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyReportRoute = StrategyReportRouteImport.update({
  id: '/strategy-report',
  path: '/strategy-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-profile': typeof BrandProfileRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/past-reports': typeof PastReportsRoute
  '/signup': typeof SignupRoute
  '/strategy-report': typeof StrategyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-profile': typeof BrandProfileRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/past-reports': typeof PastReportsRoute
  '/signup': typeof SignupRoute
  '/strategy-report': typeof StrategyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-profile': typeof BrandProfileRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/past-reports': typeof PastReportsRoute
  '/signup': typeof SignupRoute
  '/strategy-report': typeof StrategyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-profile'
    | '/login'
    | '/overview'
    | '/past-reports'
    | '/signup'
    | '/strategy-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-profile'
    | '/login'
    | '/overview'
    | '/past-reports'
    | '/signup'
    | '/strategy-report'
  id:
    | '__root__'
    | '/'
    | '/brand-profile'
    | '/login'
    | '/overview'
    | '/past-reports'
    | '/signup'
    | '/strategy-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandProfileRoute: typeof BrandProfileRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PastReportsRoute: typeof PastReportsRoute
  SignupRoute: typeof SignupRoute
  StrategyReportRoute: typeof StrategyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-profile': {
      id: '/brand-profile'
      path: '/brand-profile'
      fullPath: '/brand-profile'
      preLoaderRoute: typeof BrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/past-reports': {
      id: '/past-reports'
      path: '/past-reports'
      fullPath: '/past-reports'
      preLoaderRoute: typeof PastReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy-report': {
      id: '/strategy-report'
      path: '/strategy-report'
      fullPath: '/strategy-report'
      preLoaderRoute: typeof StrategyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandProfileRoute: BrandProfileRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PastReportsRoute: PastReportsRoute,
  SignupRoute: SignupRoute,
  StrategyReportRoute: StrategyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
